name: SwiftLint
on:
  workflow_dispatch:
  workflow_call:
jobs:
  SwiftLint:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint with --strict
        run: swiftlint --strict
