name: SwiftLint
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
jobs:
  SwiftLint:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint with --strict
        run: swiftlint --strict
        # uses: norio-nomura/action-swiftlint@3.2.1
        # with:
        #   args: --strict
